// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904052726_AddDestinationTiming")]
    partial class AddDestinationTiming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Destination", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BestSeason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("interval");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("interval");

                    b.Property<int>("TypicalDurationMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BestSeason = "All Year",
                            CloseTime = new TimeSpan(0, 17, 30, 0, 0),
                            District = "Matale",
                            Name = "Sigiriya Rock Fortress",
                            OpenTime = new TimeSpan(0, 6, 30, 0, 0),
                            TypicalDurationMinutes = 180
                        },
                        new
                        {
                            Id = 2L,
                            BestSeason = "Dec-Jul",
                            CloseTime = new TimeSpan(0, 18, 0, 0, 0),
                            District = "Hambantota",
                            Name = "Yala National Park",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            TypicalDurationMinutes = 240
                        },
                        new
                        {
                            Id = 3L,
                            BestSeason = "May-Sep",
                            CloseTime = new TimeSpan(0, 23, 59, 59, 0),
                            District = "Ampara",
                            Name = "Arugam Bay Surf Point",
                            OpenTime = new TimeSpan(0, 0, 0, 0, 0),
                            TypicalDurationMinutes = 240
                        },
                        new
                        {
                            Id = 4L,
                            BestSeason = "Dec-Mar",
                            CloseTime = new TimeSpan(0, 14, 0, 0, 0),
                            District = "Matara",
                            Name = "Mirissa Whale Watching",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            TypicalDurationMinutes = 300
                        });
                });

            modelBuilder.Entity("backend.Models.Itinerary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("backend.Models.ItineraryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<long>("ItineraryId")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("ItineraryId");

                    b.ToTable("ItineraryItems");
                });

            modelBuilder.Entity("backend.Models.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RestaurantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("backend.Models.Restaurant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AveragePrice = 1500m,
                            CuisineType = "Kottu",
                            Location = "Colombo 07",
                            Name = "Kottu Labs",
                            OpeningHours = "11:00 AM - 11:00 PM"
                        },
                        new
                        {
                            Id = 2L,
                            AveragePrice = 3000m,
                            CuisineType = "North Indian",
                            Location = "Colombo 03",
                            Name = "The Mango Tree",
                            OpeningHours = "12:00 PM - 10:30 PM"
                        },
                        new
                        {
                            Id = 3L,
                            AveragePrice = 2000m,
                            CuisineType = "Sri Lankan Rice & Curry",
                            Location = "Colombo 07",
                            Name = "Upali's by Nawaloka",
                            OpeningHours = "11:30 AM - 10:30 PM"
                        });
                });

            modelBuilder.Entity("backend.Models.SavedTransportPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TransportRouteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TravelerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TransportRouteId");

                    b.ToTable("SavedTransportPlans");
                });

            modelBuilder.Entity("backend.Models.TransportRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EstimatedCostLKR")
                        .HasColumnType("numeric");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransportMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransportRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Destination = "Ella",
                            DistanceKm = 200m,
                            EstimatedCostLKR = 1200m,
                            EstimatedDurationMinutes = 540,
                            Origin = "Colombo",
                            TransportMode = "Train"
                        },
                        new
                        {
                            Id = 2L,
                            Destination = "Ella",
                            DistanceKm = 200m,
                            EstimatedCostLKR = 25000m,
                            EstimatedDurationMinutes = 300,
                            Origin = "Colombo",
                            TransportMode = "Taxi"
                        },
                        new
                        {
                            Id = 3L,
                            Destination = "Colombo",
                            DistanceKm = 115m,
                            EstimatedCostLKR = 800m,
                            EstimatedDurationMinutes = 210,
                            Origin = "Kandy",
                            TransportMode = "Bus"
                        },
                        new
                        {
                            Id = 4L,
                            Destination = "Colombo",
                            DistanceKm = 115m,
                            EstimatedCostLKR = 600m,
                            EstimatedDurationMinutes = 180,
                            Origin = "Kandy",
                            TransportMode = "Train"
                        },
                        new
                        {
                            Id = 5L,
                            Destination = "Colombo",
                            DistanceKm = 125m,
                            EstimatedCostLKR = 1000m,
                            EstimatedDurationMinutes = 90,
                            Origin = "Galle",
                            TransportMode = "Bus"
                        });
                });

            modelBuilder.Entity("backend.Models.ItineraryItem", b =>
                {
                    b.HasOne("backend.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Itinerary", "Itinerary")
                        .WithMany("Items")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("backend.Models.Reservation", b =>
                {
                    b.HasOne("backend.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("backend.Models.SavedTransportPlan", b =>
                {
                    b.HasOne("backend.Models.TransportRoute", "TransportRoute")
                        .WithMany()
                        .HasForeignKey("TransportRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportRoute");
                });

            modelBuilder.Entity("backend.Models.Itinerary", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
